//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureBot.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks {0}. You are now logged in..
        /// </summary>
        internal static string AzureAuthDialog_LoggedIn {
            get {
                return ResourceManager.GetString("AzureAuthDialog_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be authenticated in Azure to access your subscription. Please, use the following url to log into your Azure account: {0}.
        /// </summary>
        internal static string AzureAuthDialog_NeedToLogIn {
            get {
                return ResourceManager.GetString("AzureAuthDialog_NeedToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the subscription you want to work with: {||}.
        /// </summary>
        internal static string EntityForms_SubscriptionForm_Prompt {
            get {
                return ResourceManager.GetString("EntityForms_SubscriptionForm_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Would you like to {Operation} virtual machine &apos;{VirtualMachine}&apos;?&quot;.
        /// </summary>
        internal static string EntityForms_VirtualMachineForm_Confirm {
            get {
                return ResourceManager.GetString("EntityForms_VirtualMachineForm_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the virtual machine you want to {Operation}: {||}.
        /// </summary>
        internal static string EntityForms_VirtualMachineForm_Prompt {
            get {
                return ResourceManager.GetString("EntityForms_VirtualMachineForm_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resume!.
        /// </summary>
        internal static string OAuthCallback_CannotResume {
            get {
                return ResourceManager.GetString("OAuthCallback_CannotResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in! Continue talking to the bot..
        /// </summary>
        internal static string OAuthCallback_LoggedIn {
            get {
                return ResourceManager.GetString("OAuthCallback_LoggedIn", resourceCulture);
            }
        }
    }
}
